# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sprios_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sprios_ios
  pod 'Alamofire', '~> 5.5'

end
